(function () {
  let tileList = [
    'alternating-brick-floor',
    'brazier-half-door',
    'brick-corner',
    'brick-edge',
    'brick-wall',
    'bubble-floor',
    'bubbles',
    'cave-corner',
    'cave-edge',
    'cave-floor',
    'cave-wall',
    'cement-corner',
    'cement-edge',
    'cement-wall',
    'chest',
    'diamond-tile-floor',
    'door',
    'doorway',
    'double-brazier',
    'gelatinous-cube',
    'green-potion',
    'lawn-bottom-corner',
    'lawn-side',
    'lawn-top-corner',
    'locked-door',
    'mimic',
    'one-way-door',
    'red-potion',
    'shallow-water',
    'sigil-floor-tile',
    'simple-door',
    'square-bubble-floor',
    'stairs-door',
    'stairs-down',
    'statue',
    'suit-of-armor',
    'tile-floor',
  ];
  window.listTiles = function () {
    tileList.sort();
    return tileList;
  };
})();
