(function(){
  window.GameData = {
    map:{
      tabSize:4,
      rows:[
        "...............",
        "...............",
        "...............",
        "...............",
        "........^......",
        "\\......./======",
        "~\\../=#=/......",
        "~~==/..........",
        "~\\.............",
        "~~~~\\..........",
        "~~~~~~\\........"
      ],
      legend:{
        ".":"Open Space",
        "^":"House",
        "#":"Bridge",
        "~=\\/":"Water"
      },
    },
    prologue:[
      "",
      "The Adventures Of Vox Machina: Chapter Zero - On The Road To Kraghammer",
      "",
      "Upon reuniting at the newly-constructed Greyskull Keep, the much celebrated",
      "heroes of Emon, Vox Machina, are hired by their good friend Arcanist Allura",
      "Vysoren of the Tal'Dorei council to aid her dear friend, Lady Kima of Vord,",
      "paladin of Bahamut The Platinum Dragon, in her vision quest which has taken",
      "her to the subterranean Dwarvish city of Kraghammer days prior.",
      "",
      "However, our heroes, on the road to Kraghammer, find themselves somewhat worse",
      "for wear after a less than ideal family reunion for our goliath barbarian,",
      "down one Dragonborn Sorcerer, and ambushed by an Orcish war council...",
      ""
    ],
    characterSheets:[{
      name:"Percy",
      attack:{
        name:"Pepperbox",
        bonus:12,
        range:[80,160],
        perTurn:3,
        damage:[{
          roll:"d10",
          bonus:6,
          type:"piercing"
        }]
      },
      armor:18,
      movement:30,
      initiative:8,
      size:"medium",
      maxHealth:81,
      loc:"A5"
    },{
      name: "Vex",
      attack:{
        name:"Longbow",
        bonus:13,
        range:[80,160],
        perTurn:2,
        damage:[{
          roll:"d8",
          type:"piercing",
          bonus:7
        }]
      },
      armor:19,
      movement:30,
      initiative:5,
      size:"medium",
      maxHealth:72,
      loc:"B6"
    },{
      name: "Keyleth",
      attack:{
        name:"Thorn Whip",
        bonus:10,
        range:[30],
        damage:[{
          type:"piercing",
          roll:"2d6"
        }]
      },
      armor:17,
      movement:30,
      initiative:2,
      size:"medium",
      maxHealth:71,
      loc:"C5"
    },{
      name: "Scanlan",
      attack:{
        name:"Bigby's Hand",
        bonus:10,
        range:[30],
        damage:[{
          type:"force",
          roll:"4d8"
        }]
      },
      armor:17,
      movement:25,
      initiative:2,
      size:"medium",
      maxHealth:59,
      loc:"E4"
    },{
      name: "Grog",
      attack:{
        name:"Flaming Warhammer",
        bonus:9,
        damage:[{
          type:"bludgeoning",
          roll:"d10",
          bonus:8
        },{
          type:"fire",
          roll:"d6"
        }]
      },
      armor:19,
      movement:50,
      initiative:2,
      size:"medium",
      maxHealth:134,
      loc:"E6"
    },{
      name: "Pike",
      attack:{
        name:"Mace Of Disruption",
        bonus:5,
        damage:[{
          type:"bludgeoning",
          roll:"2d6",
          bonus:1
        }]
      },
      armor:20,
      movement:25,
      initiative:0,
      size:"medium",
      maxHealth:73,
      loc:"J9"
    },{
      name:"Vax",
      attack:{
        name:"Dagger/Dagger/Dagger",
        bonus:8,
        perTurn:3,
        damage:[{
          type:"slashing",
          roll:"1d4",
          bonus:6
        }]
      },
      armor:17,
      movement:30,
      initiative:5,
      size:"medium",
      maxHealth:66,
      loc:"G9"
    }],
    foes:[{
      name:"Ner'zhul",
      type:"Orc War Chief",
      loc:"J4"
    },{
      name:"Vol'jin",
      type:"Orc War Chief",
      loc:"F4"
    },{
      name:"Thrall",
      type:"Orc War Chief",
      loc:"J8"
    },{
      name:"Xaakt",
      type:"Orc War Chief",
      loc:"K11"
    },{
      name:"Paghorim",
      type:"Orc War Chief",
      loc:"E2"
    }],
    monsters:[{
      type:"Orc War Chief",
      maxHealth:93,
      size:"medium",
      attack:{
        name:"Warpike",
        bonus:6,
        perTurn:2,
        damage:[{
          type:"bludgeoning",
          roll:"2d8",
          bonus:4
        }]
      },
      armor:16,
      movement:60,
      initiative:1,
      strategy:"distance, armor, health"
    }],
    item:[{
      name:"Leather",
      heft:"light",
      wear:"armor",
      cost:{
        value:10,
        unit:"gold"
      },
      effect:{armor:"${dexterity}+11"},
      weight:10
    },{
      name:"Studded Leather",
      heft:"light",
      wear:"armor",
      cost:{
        value:45,
        unit:"gold"
      },
      effect:{armor:"${dexterity}+12"},
      weight:13
    },{
      name:"Hide",
      heft:"Medium",
      wear:"armor",
      cost:{
        value:10,
        unit:"gold"
      },
      effect:{armor:"(${dexterity}>2?2:${dexterity})+12"},
      weight:12
    },{
      name:"Chain Shirt",
      heft:"Medium",
      wear:"armor",
      cost:{
        value:50,
        unit:"gold"
      },
      effect:{armor:"(${dexterity}>2?2:${dexterity})+13"},
      weight:20
    },{
      name:"Scale Mail",
      heft:"Medium",
      wear:"armor",
      cost:{
        value:50,
        unit:"gold"
      },
      effect:{armor:"(${dexterity}>2?2:${dexterity})+14"},
      weight:45
    },{
      name:"Breastplate",
      heft:"Medium",
      wear:"armor",
      cost:{
        value:400,
        unit:"gold"
      },
      effect:{armor:"(${dexterity}>2?2:${dexterity})+14"},
      weight:20
    },{
      name:"Ring Mail",
      heft:"Heavy",
      wear:"armor",
      cost:{
        value:30,
        unit:"gold"
      },
      effect:{armor:"14"},
      weight:40
    },{
      name:"Chain Mail",
      heft:"Heavy",
      wear:"armor",
      cost:{
        value:75,
        unit:"gold"
      },
      effect:{armor:"16"},
      weight:55
    },{
      name:"Splint",
      heft:"Heavy",
      wear:"armor",
      cost:{
        value:200,
        unit:"gold"
      },
      effect:{armor:"17"},
      weight:60
    },{
      name:"Shield",
      wield:1,
      cost:{
        value:10,
        unit:"gold"
      },
      effect:{armor:"${armor}+2"},
      weight:6
    },{
      name:"Club",
      class:"simple",
      heft:"Light",
      wield:1,
      cost:{
        value:1,
        unit:"silver"
      },
      weight:2,
      damage:{
        bludgeoning:"1d4"
      }
    },{
      name:"Dagger",
      class:"simple",
      heft:"Light",
      wield:1,
      cost:{
        value:2,
        unit:"gold"
      },
      weight:1,
      damage:{
        piercing:"1d4"
      },
      properties:{
        Finesse:true,
        Thrown:[20,60]
      }
    },{
      name:"Greatclub",
      class:"simple",
      wield:2,
      cost:{
        value:2,
        unit:"silver"
      },
      weight:10,
      damage:{
        bludgeoning:"1d8"
      }
    },{
      name:"Handaxe",
      class:"simple",
      heft:"Light",
      wield:1,
      cost:{
        value:5,
        unit:"gold"
      },
      weight:2,
      damage:{
        slashing:"1d6"
      },
      properties:{
        Thrown:[20,60]
      }
    },{
      name:"Javelin",
      class:"simple",
      wield:1,
      cost:{
        value:5,
        unit:"silver"
      },
      weight:2,
      damage:{
        piercing:"1d6"
      },
      properties:{
        Thrown:[30,120]
      }
    },{
      name:"Light Hammer",
      class:"simple",
      heft:"Light",
      wield:1,
      cost:{
        value:2,
        unit:"gold"
      },
      weight:2,
      damage:{
        bludgeoning:"1d4"
      },
      properties:{
        Thrown:[20,60]
      }
    },{
      name:"Mace",
      class:"simple",
      wield:1,
      cost:{
        value:5,
        unit:"gold"
      },
      weight:4,
      damage:{
        bludgeoning:"1d6"
      }
    },{
      name:"Quarterstaff",
      class:"simple",
      wield:1,
      cost:{
        value:2,
        unit:"silver"
      },
      weight:4,
      damage:{
        bludgeoning:["1d6","1d8"]
      }
    },{
      name:"Spear",
      class:"simple",
      wield:1,
      cost:{
        value:1,
        unit:"gold"
      },
      weight:3,
      damage:{
        piercing:["1d6","1d8"]
      },
      properties:{
        Thrown:[20,60]
      }
    },{
      name:"Light Crossbow",
      class:"simple",
      wield:2,
      cost:{
        value:25,
        unit:"gold"
      },
      weight:5,
      damage:{
        piercing:"1d8"
      },
      properties:{
        loading:true,
        Ammunition:[80,320]
      }
    },{
      name:"Shortbow",
      class:"simple",
      wield:2,
      cost:{
        value:25,
        unit:"gold"
      },
      weight:2,
      damage:{
        piercing:"1d6"
      },
      properties:{
        Ammunition:[80,320]
      }
    },{
      name:"Battleaxe",
      class:"martial",
      wield:1,
      cost:{
        value:10,
        unit:"gold"
      },
      weight:4,
      damage:{
        slashing:["1d8","1d10"]
      }
    },{
      name:"Greataxe",
      class:"martial",
      heft:"Heavy",
      wield:2,
      cost:{
        value:30,
        unit:"gold"
      },
      weight:7,
      damage:{
        slashing:"1d12"
      }
    },{
      name:"Greatsword",
      class:"martial",
      heft:"Heavy",
      wield:2,
      cost:{
        value:50,
        unit:"gold"
      },
      weight:6,
      damage:{
        slashing:"2d6"
      }
    },{
      name:"Longsword",
      class:"martial",
      wield:1,
      cost:{
        value:15,
        unit:"gold"
      },
      weight:3,
      damage:{
        slashing:["1d8","1d10"]
      }
    },{
      name:"Maul",
      class:"martial",
      heft:"Heavy",
      wield:2,
      cost:{
        value:10,
        unit:"gold"
      },
      weight:10,
      damage:{
        bludgeoning:"2d6"
      }
    },{
      name:"Morningstar",
      class:"martial",
      wield:1,
      cost:{
        value:15,
        unit:"gold"
      },
      weight:4,
      damage:{
        piercing:"1d8"
      }
    },{
      name:"Rapier",
      class:"martial",
      wield:1,
      cost:{
        value:15,
        unit:"gold"
      },
      weight:2,
      damage:{
        piercing:"1d8"
      },
      properties:{
        finesse:true
      }
    },{
      name:"Scimitar",
      class:"martial",
      heft:"Light",
      wield:1,
      cost:{
        value:25,
        unit:"gold"
      },
      weight:3,
      damage:{
        piercing:"1d6"
      },
      properties:{
        finesse:true
      }
    },{
      name:"Shortsword",
      class:"martial",
      heft:"Light",
      wield:1,
      cost:{
        value:10,
        unit:"gold"
      },
      weight:2,
      damage:{
        piercing:"1d6"
      },
      properties:{
        finesse:true
      }
    },{
      name:"Trident",
      class:"martial",
      wield:1,
      cost:{
        value:5,
        unit:"gold"
      },
      weight:4,
      damage:{
        piercing:["1d6","1d8"]
      },
      properties:{
        Thrown:[20,60]
      }
    },{
      name:"Warhammer",
      class:"martial",
      wield:1,
      cost:{
        value:15,
        unit:"gold"
      },
      weight:2,
      damage:{
        bludgeoning:["1d8","1d10"]
      }
    },{
      name:"Hand Crossbow",
      class:"martial",
      heft:"Light",
      wield:1,
      cost:{
        value:75,
        unit:"gold"
      },
      weight:3,
      damage:{
        piercing:"1d6"
      },
      properties:{
        loading:true,
        Ammunition:[30,120]
      }
    },{
      name:"Heavy Crossbow",
      class:"martial",
      heft:"Heavy",
      wield:2,
      cost:{
        value:50,
        unit:"gold"
      },
      weight:18,
      damage:{
        piercing:"1d10"
      },
      properties:{
        loading:true,
        Ammunition:[100,400]
      }
    },{
      name:"Longbow",
      class:"martial",
      heft:"Heavy",
      wield:2,
      cost:{
        value:50,
        unit:"gold"
      },
      weight:2,
      damage:{
        piercing:"1d8"
      },
      properties:{
        Ammunition:[150,600]
      }
    }],
    "conditions":[{
      name:"Prone"
    }]
  };
})();
